config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :jobs do
    resources :appointments, only: %i[new create show]
    resources :job_applications, only: %i[new create]
    resources :appointments, only: %i[new create show]
    resources :favorites, only: %i[new create show]
  end
  resources :chatrooms, only: %i[index show] do
    resources :messages, only: :create
  end

  resources :job_applications, only: %i[index destroy] do
    resources :chatrooms, only: :create
    member do
      patch :accept
      patch :decline
    end
  end

  resources :favorites, only: %i[index destroy]
  resources :appointments, only: :index

  # Pages Controller Routes
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'
  get '/cvs', to: 'pages#cvs'
  get '/calendar', to: 'pages#calendar'
  get '/employer_calendar', to: 'pages#employer_calendar'
  get '/candidates', to: 'pages#employer_index'
  get '/candidates/:id', to: 'pages#candidates_show', as: :candidate
  get '/employer', to: 'pages#employer_profile', as: :employer_profile
  get '/my_posts', to: 'pages#my_posts', as: :my_posts
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :destroy]

  def index
    @favorites = Favorite.where(user_id: current_user.id)
  end

  def show
  end

  def create
    @favorite = Favorite.new
    @job = Job.find(params[:job_id])
    @favorite.job = @job
    @favorite.user = current_user
    if @favorite.save
      redirect_to @job
    else
      render 'jobs/show', status: :unprocessable_entity
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @job = @favorite.job_id
    if current_user == @favorite.user
      @favorite.destroy
      redirect_to job_path(@job), notice: 'Job position was successfully destroyed.'
    else
      redirect_to favorites_path, alert: 'You are not authorized to perform this action.'
    end
  end

  private

  def favorite_params
    params.require(:favorite)
  end

  def set_favorite
    @favorite = Favorite.find(params[:id])
  end
end

app/views/favorites/index.html.erb
<div class="container customize-container">
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "My profile", dashboard_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
   <%= link_to "My favorites", favorites_path, class: "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to "My CVs", cvs_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "My calendar", calendar_path, class: "nav-link" %>
  </li>
</ul>
<div class="cards main-container">
<div class="py-5 mb-5">
  <div class="row justify-content-center">
<% @favorites.each do |favorite| %>
  <div class="col-12 col-lg-3">
    <div class="card box-shadow my-3">
    <%#= image_tag "#{favorite.job.level}.jpg", class: "card-img-top", height: 200%>
      <div class="card-body">
      <div class="row">
      <div class="col-8">
       <strong> <p class="card-title"><i class="fa-solid fa-user-large"></i> <%= favorite.job.position %></p></strong>
       </div>
       <div class="col-4">
        <p class="card-title"><i class="fa-solid fa-location-dot"></i> Berlin</p>
        </div>
        <p class="card-title"> <i class="fa-solid fa-hand-holding-dollar"></i> <%= favorite.job.salary %> </p>
        <p class="card-title"> <i class="fas fa-reply-all"></i> <%= favorite.job.level %> </p>
        <%= image_tag "#{favorite.job.level}.png", class: "card-img-top", height: 200%>
      <div class="row">
      <div class="col-6">
        <%#= link_to "Apply", chatrooms_path, class: "card-button mb-3 mx-2", style: "width: 100px" %>
          <%= button_to "Apply", job_job_applications_path(favorite.job), method: :post, class: "card-button mb-3 mx-", style: "width: 100px;" %>
      </div>
      <div class="col-6">
        <%= link_to "Delete", favorite_path(favorite), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
          class: "card-button mb-3 mx-3", style: "width: 100px" %>
        </div>
      </div>
      </div>
      </div>
    </div>
  </div>
<% end %>
</div>
</div>
</div>
</div>