config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :jobs do
    resources :appointments, only: %i[new create show]
    resources :job_applications, only: %i[new create]
    resources :appointments, only: %i[new create show]
    resources :favorites, only: %i[new create show]
  end
  resources :chatrooms, only: %i[index show] do
    resources :messages, only: :create
  end

  resources :job_applications, only: %i[index destroy] do
    resources :chatrooms, only: :create
    member do
      patch :accept
      patch :decline
    end
  end

  resources :favorites, only: %i[index destroy]
  resources :appointments, only: :index

  # Pages Controller Routes
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'
  get '/cvs', to: 'pages#cvs'
  get '/calendar', to: 'pages#calendar'
  get '/employer_calendar', to: 'pages#employer_calendar'
  get '/candidates', to: 'pages#employer_index'
  get '/candidates/:id', to: 'pages#candidates_show', as: :candidate
  get '/employer', to: 'pages#employer_profile', as: :employer_profile
  get '/my_posts', to: 'pages#my_posts', as: :my_posts
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :user
  belongs_to :job
  has_many :chatrooms, dependent: :destroy
  enum :status, %i[pending accepted declined], default: :pending
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :set_app, only: %i[show destroy]

  def index
    all_jobs = current_user.jobs.includes(:job_applications)
    @jobs = all_jobs.reject do |job|
      job.job_applications.empty?
    end
  end

  # def show
  #   @job_application = JobApplication.find(params[:id])
  #   @job = @job_application.job
  # end

  def create
    @job = Job.find(params[:job_id])
    @app = @job.job_applications.new(user: current_user)
    if @app.save
      redirect_to job_path(@job)
    else
      render 'job_applications/show', status: :unprocessable_entity
    end
  end

  def accept
    @app = JobApplication.find(params[:id])
    @app.status = "accepted"
    @app.save
    redirect_to job_applications_path, status: :see_other
  end

  def decline
    @app = JobApplication.find(params[:id])
    @app.status = "declined"
    @app.save
    redirect_to job_applications_path, status: :see_other
  end

  def destroy
    @app.destroy
  end

  private

  def app_params
    params.require(:app).permit(:status)
  end

  def set_app
    @favorite = JobApplication.find(params[:id])
  end

end

app/views/job_applications/index.html.erb
<div class="container customize-container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "My profile", employer_profile_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "My posts", my_posts_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Job applications", job_applications_path, class: "nav-link  active" %>
    </li>
    <li class="nav-item">
      <%= link_to "My calendar", employer_calendar_path, class: "nav-link" %>
    </li>
  </ul>
  <div class="cards main-container">
    <div class="py-5 mb-5">
        <div class="row justify-content-center">
          <% @jobs.each do |job| %>
            <h2><%= job.position %></h2>
            <% job.job_applications.each do |application| %>
              <div class="col-12 col-lg-3">
                <div class="card employer-card-box-shadow my-3">
                  <%= image_tag "#{job.level}.png", class: "card-img-top", height: 200 %>
                  <div class="card-body">
                    <div class="row">
                    <h5 class="card-title", style="text-align: center; margin-bottom: 15px;" ><b><%= job.position %></b></h5>
                    <p class="card-title"> <i class="fa-solid fa-hand-holding-dollar"></i>  <%= job.salary %> €</p>
                    <p class="card-title"> <i class="fa-solid fa-location-dot"></i>  <%= job.address %> </p>
                    <p class="card-text", style="margin-top: 10px; text-align: center; font-size: 18px;"><b><%= application.user.first_name %> <%= application.user.last_name %></b> wants to apply</p>
                    <p class="card-text", style="text-align: center; font-size: 18px;">
                      The request is:  <br>
                      <span style="background-color: yellow; font-size: 18px; font-weight: bold;"><%= application.status.upcase %></span> <br>
                      </p>
                      <% if application.pending? %>
                        <%= link_to "Accept", accept_job_application_path(application), class: "button-success mb-3", data: {turbo_method: :patch}%>
                        <div class="row">
                        <div class="col-6">
                        <p class="card-text", style="text-align: center;">
                          <%= link_to "Decline", decline_job_application_path(application), style: "text-decoration: none; color: red;", data: {turbo_method: :patch} %>
                        </p>
                        </div>
                        <div class="col-6">
                        <p class="card-text", style="text-align: center; text-decoration: none !important;"><%= link_to "#{application.user.first_name}'s profile", candidate_path(application.user.id), style: "text-decoration: none;" %></p>
                      </div>
                      </div>
                      <% elsif application.accepted? %>
                        <%= link_to "Make an appointment", new_job_appointment_path(job), class: "button-neutral mb-3"%>
                      <p class="card-text", style="text-align: center;"><%= link_to "Decline", decline_job_application_path(application), style: "text-decoration: none; color: red;", data: {turbo_method: :patch} %></p>
                      <% end %>
                      </div>
                    </div>
                  </div>
              </div>
            <% end %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/job_applications/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random/?work);">
  <div class="container">
    <h1><i class="fa-solid fa-user-large"></i> <strong><%= @job.position %></strong></h1>
    <p>
        <i class="fa-solid fa-hand-holding-dollar"></i> <%= @job.salary %> <i class="fa-solid fa-euro-sign"></i>
        <br>
        <i class="fa-solid fa-location-dot"></i> <%= @job.address %>
        <br>
        <i class="fa-solid fa-suitcase"></i> <%= @job.level %>
        <br>
        <i class="fa-solid fa-user-doctor"></i> <%= @job.description %>
        <br>
    </p>
    <div class="d-flex">
      <%= link_to "DM HR manager", job_application_chatrooms_path(@job_application), class: "button-neutral", style: "width: 200px; line-height: 35px;", data: {turbo_method: :post} %>
      <div class="flash flash-success alert-dismissible fade show" role="alert">
        <span><strong>Yay!</strong> 🎉 you successfully applied for the job!</span>
        <a data-bs-dismiss="alert" aria-label="Close">
          <i class="fas fa-times"></i>
        </a>
      </div>
    </div>
  </div>
</div>