config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :jobs do
    resources :appointments, only: %i[new create show]
    resources :job_applications, only: %i[new create]
    resources :appointments, only: %i[new create show]
    resources :favorites, only: %i[new create show]
  end
  resources :chatrooms, only: %i[index show] do
    resources :messages, only: :create
  end

  resources :job_applications, only: %i[index destroy] do
    resources :chatrooms, only: :create
    member do
      patch :accept
      patch :decline
    end
  end

  resources :favorites, only: %i[index destroy]
  resources :appointments, only: :index

  # Pages Controller Routes
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'
  get '/cvs', to: 'pages#cvs'
  get '/calendar', to: 'pages#calendar'
  get '/employer_calendar', to: 'pages#employer_calendar'
  get '/candidates', to: 'pages#employer_index'
  get '/candidates/:id', to: 'pages#candidates_show', as: :candidate
  get '/employer', to: 'pages#employer_profile', as: :employer_profile
  get '/my_posts', to: 'pages#my_posts', as: :my_posts
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="text-center text-white">
<% if user_signed_in? %>
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgb(211,211,211);">
    © 2023 Copyright:
    <a class="text-white" href="http://www.traumjob.site/">traumjob.site</a>
  </div>
  <!-- Copyright -->
        <% else %>
  <div class="text-center p-3" style="background-color: rgb(211,211,211);">
    © 2023 Copyright:
    <a class="text-white" href="http://www.traumjob.site/">traumjob.site</a>
  </div>
<% end %>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
                <li class="nav-item active">
                  <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
              <% if current_user.job_seeker == true %>
                <li class="nav-item active">
                  <%= link_to "Jobs", jobs_path, class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item active">
                  <%= link_to "Candidates", candidates_path, class: "nav-link" %>
                </li>
                <li class="nav-item active">
                <%= link_to "Post a Job", new_job_path, class: "nav-link" %>
                </li>
              <% end %>
            <li class="nav-item">
              <%= link_to "Messages", chatrooms_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%= cl_image_tag current_user.avatar.key, :width => 40, :height => 40, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <% if current_user.job_seeker == true %>
                    <%= link_to "My profile", dashboard_path, class: "dropdown-item" %>
                  <% else %>
                    <%= link_to "My profile", employer_profile_path, class: "dropdown-item" %>
                  <% end %>
                  <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                </div>
            </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>