config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :jobs do
    resources :appointments, only: %i[new create show]
    resources :job_applications, only: %i[new create]
    resources :appointments, only: %i[new create show]
    resources :favorites, only: %i[new create show]
  end
  resources :chatrooms, only: %i[index show] do
    resources :messages, only: :create
  end

  resources :job_applications, only: %i[index destroy] do
    resources :chatrooms, only: :create
    member do
      patch :accept
      patch :decline
    end
  end

  resources :favorites, only: %i[index destroy]
  resources :appointments, only: :index

  # Pages Controller Routes
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'
  get '/cvs', to: 'pages#cvs'
  get '/calendar', to: 'pages#calendar'
  get '/employer_calendar', to: 'pages#employer_calendar'
  get '/candidates', to: 'pages#employer_index'
  get '/candidates/:id', to: 'pages#candidates_show', as: :candidate
  get '/employer', to: 'pages#employer_profile', as: :employer_profile
  get '/my_posts', to: 'pages#my_posts', as: :my_posts
end

app/views/pages/calendar.html.erb
<div class="container">
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "My profile", dashboard_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
   <%= link_to "My favorites", favorites_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "My CVs", cvs_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "My calendar", calendar_path, class: "nav-link active" %>
  </li>
</ul>
 <%= month_calendar(events: @appointments, attribute: :date) do |date, appointments| %>
  <%= date %>

  <% appointments.each do |appointment| %>
    <div class="appointment" style="width: 200px;">
      <p><%= appointment.name %></p>
  <% end %>
    </div>
<% end %>
</div>

app/views/pages/candidates_show.html.erb
<section class="h-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background-color: #36A9AE; height:200px;">
            <div>
                <%= cl_image_tag @user.avatar.key, class:"img-thumbnail mt-4 mb-2", style:"height:177px; width:150px;"%>
            </div>
            <div class="ms-3" style="margin-top: 150px;">
              <h3><%= @user.first_name %> <%= @user.last_name %></h3>
            </div>
          </div>
          <div class="card-body p-4 text-black">
            <div class="mb-5">
              <div class="p-4" style="background-color: #f8f9fa;">
              <p class="lead fw-normal mb-1">About</p>
                <p class="font-italic mb-1"><%= @user.profile_description %></p>
              </div>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-4">
              <p class="lead fw-normal mb-0">Candidate's Cvs</p>
              <p class="mb-0"><a href="#!" class="text-muted">Show all</a></p>
            </div>
            <div class="row g-2">
              <% @user.cvs.each do |cv| %>
              <div class="col mb-2">
              <% cv.url %>
                  <iframe src="<%= cl_image_path(cv.key, secure: true) %>" width="70%" height="650"></iframe>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

app/views/pages/candidatesindex.html.erb
  <h1>Employer Index</h1>
  <div class="cards">
    <% @users.each do |user|%>
      <div style="background-image: url('<%= cl_image_path user.avatar.key if user.avatar.key %>')"></div>
      <p>Name: <%= user.first_name %></p>
      <p>Lastname: <%= user.last_name %></p>
      <%= link_to "See profile", candidatesshow_path(user.id) %>
    <% end %>
  </div>

app/views/pages/cvs.html.erb
<div class="container">
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "My profile", dashboard_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
   <%= link_to "My favorites", favorites_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "My CVs", cvs_path, class: "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to "My calendar", calendar_path, class: "nav-link" %>
  </li>
</ul>
      <% if current_user.cvs != [] %>
        <% current_user.cvs.each do |cv| %>
          <div>
            <% cv.url %>
            <iframe src="<%= cl_image_path(cv.key, secure: true) %>"
            style="
                      display: block;
                      margin: 0 auto;
                      border: 1px solid #ccc;
                      box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);
                      height: 470px;
                      margin-top: 20px;">
            </iframe>
          </div>
        <% end %>
      <% end %>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "My profile", dashboard_path, class: "nav-link active" %>
  </li>
  <li class="nav-item">
   <%= link_to "My favorites", favorites_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "My CVs", cvs_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "My calendar", calendar_path, class: "nav-link" %>
  </li>
</ul>
<div class="user-profile">
<div class="row">
<div class="col-6">
<%= cl_image_tag current_user.avatar.key, style:"width:400px; height:400px; object-fit:cover;", class: "avatar dropdown-toggle mt-5 mb-5  ", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
</div>
<div class="col-6 mt-5 mb-5">
<div class="content">
<h1>Hi, my name is <%= current_user.first_name %> <%=current_user.last_name %>!</h1>
<div class="profile-description">
<h3>About me:</h3>
<p style="font-size: 20px;"><%= current_user.profile_description %></p>
<div class="d-flex">
<%= link_to "My messages", chatrooms_path, class: "card-button mb-3 mt-3 mx-3", style: "width: 200px;" %>
<%= link_to "My appointments", calendar_path, class: "search-button mb-3 mt-3", style: "width: 200px;" %>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

app/views/pages/employer_calendar.html.erb
   <div class="container">
   <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "My profile", employer_profile_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "My posts", my_posts_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Job applications", job_applications_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "My calendar", employer_calendar_path, class: "nav-link active" %>
    </li>
  </ul>
 <%= month_calendar(events: @appointments, attribute: :date) do |date, appointments| %>
  <%= date %>

  <% appointments.each do |appointment| %>
    <div class="appointment" style="width: 200px;">
      <p><%= appointment.name %></p>
  <% end %>
    </div>
<% end %>
</div>

app/views/pages/employer_index.html.erb
<div class="main-container">
<!--Search bar-->
<div class="search-body">
  <div class="search-container">
    <%= form_with url: candidates_path, method: :get, class: "d-flex ", style: "width:100%" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control input",
        placeholder: "Looking for candidates...", class: "search-input",
        style: "width:100%"
      %>
<button type="submit" class="search-btn" style="margin-left: 5px">
  <i class="fas fa-search"></i>
</button>
    <% end %>
  </div>
  </div>
  <!--User cards-->
  <div class="candidates-container">
    <% @users.each do |user|%>
    <div class="candidate-card">
    <% if user.gender == "male" %>
      <%= image_tag "Male_avatar.png", class: "candidate-card-avatar" %>
    <% else %>
      <%= image_tag "Female_avatar.png", class: "candidate-card-avatar" %>
    <% end %>
        <div class="candidate-card-details">
          <h2 style="margin-bottom: 15px;"><%= user.first_name %> <%= user.last_name %></h2>
            <p><i class="fas fa-briefcase"></i>  <span style="background-color: yellow;"><%= user.profesion %></span></p>
            <p style="margin-bottom: 0rem;"><i class="fas fa-map-marker-alt"></i>  <%= user.location %></p>
            <%= link_to "Open to work", candidate_path(user.id), class: "candidate-card-btn"%>
        </div>
      </div>
    <% end %>
    </div>
</div>

app/views/pages/employer_profile.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "My profile", employer_profile_path, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "My posts", my_posts_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Job applications", job_applications_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "My calendar", employer_calendar_path, class: "nav-link" %>
    </li>
  </ul>
  <div class="user-profile">
    <div class="row">
      <div class="col-6">
      <% if current_user.avatar.attached? %>
        <%= cl_image_tag current_user.avatar.key, style:"width:400px; height:400px; object-fit:cover;", class: "avatar dropdown-toggle mt-5 mb-5  ", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <%= image_tag "/home/trinidad/code/trinidadcerri/TraumArbeit/app/assets/images/Male_avatar.png", style:"width:400px; height:400px; object-fit:cover;", class: "avatar dropdown-toggle mt-5 mb-5  ", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
      <% end %>
      </div>
      <div class="col-6 mt-5 mb-5">
        <div class="content" style="margin-top:20px; text-align: center;">
          <h1><b><%= current_user.nickname %></b></h1>
            <div class="profile-description" style="margin-top: 80px; text-align: center;">
              <h3>About <b>the company: </b></h3>
              <p style="font-size: 20px;"><%= current_user.profile_description %></p>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<body>
<!--Banner-->
<section id="banner">
    <div class="banner-text">
        <h1><span>Dream</span><span>Job</span></h1>
          <p>
            Our goal is to make your job or candidate search <br>
            an inspiring process
          </p>
        <div class="banner-btn">
            <%= link_to(jobs_path) do %>
              <div><span></span>Find a Job</div>
            <% end %>
            <%= link_to(candidates_path) do %>
              <div><span></span>Find a Candidate</div>
            <% end %>
        </div>
    </div>
</section>

<!--Nav Bar-->
<div id="sideNav" style="right: -250px;">
    <nav>
    <ul>
        <li><a href="#banner">HOME</a></li>
        <li><a href="#feature">FEATURES</a></li>
        <li><a href="#path">YOUR PATH</a></li>
        <li><a href="#review">OUR REVIEWS</a></li>
        <li><a href="#footer">CONTACT US</a></li>
    </ul>
    </nav>
</div>
<div id="menuBtn">
      <%= image_tag "menu.png", id:"menu" %>
</div>

<!--Features-->
<section id="feature">
<div class="title-text">
<p>FEATURES</p>
<h1>How it works</h1>
</div>
<div class="feature-box">
    <div class="features">
        <h1>Create an Account</h1>
        <div class="features-desc">
            <div class="feature-icon">
                <i class="fa fa-sharp fa-light fa-user"></i>
            </div>
            <div class="feature-text">
                <p>You can Sign In in our page and have all the benefits as a Job Seeker or even as a future employer!</p>
            </div>
        </div>
        <h1>Look for a Job</h1>
        <div class="features-desc">
            <div class="feature-icon">
                <i class="fa fa-solid fa-magnifying-glass"></i>
            </div>
            <div class="feature-text">
                <p>You could look for jobs, apply for that unique opportunity, chat with your future employer or even schedule your appoiments</p>
            </div>
        </div>
        <h1>Post a new job offer</h1>
        <div class="features-desc">
            <div class="feature-icon">
                <i class="fa fa-solid fa-pen-nib"></i>
            </div>
            <div class="feature-text">
                <p>If you have already created your business and need someone on board to help you boost it, this space is also for you!</p>
            </div>
        </div>
    </div>
    <div class="features-img">
        <%= image_tag "dream_job2.jpg", class:"features-img" %>
    </div>
</div>
</section>

<!--User Paths-->
<section id="path">
    <div class="title-text">
    <p>YOUR PATH</p>
    <h1>Your options are here!</h1>
    </div>
    <div class="path-box">
        <%= link_to jobs_path, class:"links" do %>
        <div class="user-path">
            <%= image_tag "user-jobseeker.jpg" %>
            <div class="overlay"></div>
            <div class="path-desc">
                <h3>Find a Job</h3>
                <hr>
                <p>Save and apply for jobs, keep track of your journey with your own calendar and have up-to-date your cvs.</p>
            </div>
        <% end %>
        </div>
        <%= link_to candidates_path, class:"links" do %>
        <div class="user-path">
            <%= image_tag "user-employer.jpg" %>
            <div class="overlay"></div>
            <div class="path-desc">
                <h3>Find a Candidate</h3>
                <hr>
                <p>Find the right match for your company here. Talk to the candidates and schedule meetings in your calendar.</p>
            </div>
          <% end %>
        </div>
    </div>

</section>

<!--Reviews-->
<section id="review">
    <div class="title-text">
    <p>OUR REVIEWS</p>
    <h1>What users say about us</h1>
    </div>
<div class="review-row">
    <div class="review-col">
        <div class="reviewer">
            <%= image_tag "reviewer-1.jpg", class:"reviewer-img" %>
            <div class="reviewer-info">
                <h4>John W. <i class="fa-brands fa-twitter"></i></h4>
                <small>@johnw</small>
            </div>
        </div>
        <p>After my bootcamp I could not focus on another process. Traumjob secured me my dream job the day I trusted the app!</p>
    </div>
    <div class="review-col">
        <div class="reviewer">
        <%= image_tag "reviewer-2.jpg", class:"reviewer-img" %>
        <div class="reviewer-info">
            <h4>Mery M. <i class="fa-brands fa-twitter"></i></h4>
            <small>@merym</small>
        </div>
        </div>
        <p>I was unemployed and desperate. Traumjob helped me to focus, save my process and get a job in a healthy and safe way!</p>
    </div>
    <div class="review-col">
        <div class="reviewer">
        <%= image_tag "reviewer-3.jpg", class:"reviewer-img" %>
        <div class="reviewer-info">
            <h4>Adam L. <i class="fa-brands fa-twitter"></i></h4>
            <small>@adaml</small>
        </div>
        </div>
        <p>I was looking for the ideal person for a very important position in my company. The order offered by the app made the way to find him more pleasant and simple.</p>
    </div>
</div>
</section>

<!--footer-->
<footer id="footer" class="text-center text-white">
  <div class="container p-4 pb-0">
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
  </div>

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgb(211,211,211);">
    © 2023 Copyright:
    <a class="text-white" href="http://www.traumjob.site/">traumjob.site</a>
  </div>
</footer>

</section>






<script>
var menuBtn = document.getElementById("menuBtn")
var sideNav = document.getElementById("sideNav")
var menu = document.getElementById("menu")

sideNav.style.right = "-250px";

menuBtn.onclick = function(){
    if(sideNav.style.right == "-250px"){
        sideNav.style.right = "0";
        menu.setAttribute("image_tag", "menu.png" )
    }
    else{
        sideNav.style.right = "-250px";
        menu.setAttribute("image_tag", "menu.png" )
    }
}

var scroll = new SmoothScroll('a[href*="#"]', {
	speed: 1000,
	speedAsDuration: true
});

</script>
</body>

app/views/pages/my_posts.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "My profile", employer_profile_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "My posts", my_posts_path, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "Job applications", job_applications_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "My calendar", employer_calendar_path, class: "nav-link" %>
    </li>
  </ul>
  <div class="cards main-container">
    <div class="py-5 mb-5">
      <div class="row justify-content-center">
        <% current_user.jobs.each do |job| %>
          <div class="col-12 col-lg-3">
              <div class="card employer-card-box-shadow my-3">
              <%= image_tag "#{job.level}.png", class: "card-img-top", height: 200 %>
                <div class="card-body">
                  <h5 class="card-title", style="text-align: center;" ><b><%= job.position %></b></h5>
                    <p class="card-title"> <i class="fa-solid fa-hand-holding-dollar"></i>  <%= job.salary %> </p>
                    <p class="card-title"><i class="fa-solid fa-location-dot"></i> Berlin</p>
                  <div class="row">
                    <div class="col-6">
                      <%= link_to "See post", job_path(job), class: "button-success mb-3", style: "width: 120px" %>
                    </div>
                    <div class="col-6">
                      <%= link_to "Edit post", edit_job_path(job), class: "button-neutral mb-3", style: "width: 120px" %>
                    </div>
                    <p class="card-text", style="text-align: center;"><b>
                      <%= link_to "Delete the post", job_path(job), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
                    </b></p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>